"""Add phase 8 outreach CRM columns

Revision ID: 21fb659919f4
Revises: c8dbb557e7fd
Create Date: 2026-06-27 19:27:34.000007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fb659919f4'
down_revision: Union[str, Sequence[str], None] = 'c8dbb557e7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_intelligence', sa.Column('outreach_status', sa.JSON(), nullable=True))
    op.add_column('lead_intelligence', sa.Column('followups', sa.JSON(), nullable=True))
    op.add_column('lead_intelligence', sa.Column('meeting_booking', sa.JSON(), nullable=True))
    op.add_column('lead_intelligence', sa.Column('crm_update', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_intelligence', 'crm_update')
    op.drop_column('lead_intelligence', 'meeting_booking')
    op.drop_column('lead_intelligence', 'followups')
    op.drop_column('lead_intelligence', 'outreach_status')
    # ### end Alembic commands ###
