"""Part4

Revision ID: 267cd0be8626
Revises: c8c5b7d0b4db
Create Date: 2026-06-27 18:27:17.685032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267cd0be8626'
down_revision: Union[str, Sequence[str], None] = 'c8c5b7d0b4db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_business_profiles_workspace_id'), 'business_profiles', ['workspace_id'], unique=False)
    op.add_column('leads', sa.Column('workspace_id', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('workflow_state', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('requires_hitl', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    op.drop_column('leads', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    op.drop_column('leads', 'requires_hitl')
    op.drop_column('leads', 'workflow_state')
    op.drop_column('leads', 'workspace_id')
    op.drop_index(op.f('ix_business_profiles_workspace_id'), table_name='business_profiles')
    op.drop_column('business_profiles', 'workspace_id')
    # ### end Alembic commands ###
