"""Add phase 5 and 6 columns

Revision ID: c8dbb557e7fd
Revises: 267cd0be8626
Create Date: 2026-06-27 19:18:00.629995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8dbb557e7fd'
down_revision: Union[str, Sequence[str], None] = '267cd0be8626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_intelligence', sa.Column('website_audit', sa.JSON(), nullable=True))
    op.add_column('lead_intelligence', sa.Column('ai_opportunities', sa.JSON(), nullable=True))
    op.add_column('lead_intelligence', sa.Column('personalized_message', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_intelligence', 'personalized_message')
    op.drop_column('lead_intelligence', 'ai_opportunities')
    op.drop_column('lead_intelligence', 'website_audit')
    # ### end Alembic commands ###
